version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - '/frontend:/app'
    command: ["/bin/sh", "-c", "[ -d ./node_modules ] && yarn serve || [ ! -d ./node_modules ] && yarn install --prod=false"]